### ISSUE TITLE
Need better name! 

### ISSUE THREAD

**Issue by thilak-rao** [avikodak/BengaluruStartupInterviews#1]
Can we have a better name for this repository? Sounds very bland. 

I was thinking maybe "100 Startup Interviews Bangalore"

**Comment by siddhahast** [comment]
Then I can give you more coding questions I faced.

**Comment by avikodak** [comment]
Interviews @ India ?

**Comment by thilak-rao** [comment]
@avikodak, @Siddhahast: India is too generic. Let's chase the startups in Bangalore niche.

**Comment by avikodak** [comment]
Fine with me but lets not give a number like 100 lets keep it open

**Comment by thilak-rao** [comment]
Yeah.. that just some random thought that came to my head. We could choose anything. 

Marking this issue as closed.
